// src/components/TestimonialsSection.jsx
import React, { useState } from "react";
import "./TestimonialsSection.css";
import Button from "@mui/material/Button";
// filter btns icons
import HubIcon from "@mui/icons-material/Hub";
import LayersIcon from "@mui/icons-material/Layers";
import WifiChannelIcon from "@mui/icons-material/WifiChannel";
import PolylineIcon from "@mui/icons-material/Polyline";

const filters = [
  { title: "View All", icon: <LayersIcon fontSize="small" /> },
  { title: "Web Apps", icon: <HubIcon fontSize="small" /> },
  { title: "eCommerce", icon: <WifiChannelIcon fontSize="small" /> },
  { title: "Enterprise", icon: <PolylineIcon fontSize="small" /> },
];

const testimonials = [
  {
    company: `/public/images/client-logo-01.svg`,
    quote:
      "As a content creator, I was always on the lookout for a tool that could help me keep up with the demands of the modern content landscape. This tool has been a game-changer. It enhances content creation and helps me stay ahead of the curve.",
    name: "Makayla P.",
    category: "Web Apps",
  },
  {
    company: `/public/images/client-logo-02.svg`,
    quote:
      "I've tried several content generation tools, but this one stands out. The attention to detail and understanding of my brand's voice and tone is unmatched. It consistently produces content that resonates with my audience.",
    name: "Andrew K.",
    category: "eCommerce",
  },
  {
    company: `/public/images/client-logo-03.svg`,
    quote:
      "Content creation used to be a bottleneck in our workflow, but no more. This AI tool is incredibly intuitive and produces top-notch content every time. It's like having an extra team member who never sleeps.",
    name: "Lucy D.",
    category: "Web Apps",
  },
  {
    company: `/public/images/client-logo-04.svg`,
    quote:
      "The quality of the content generated by this AI tool is outstanding. It has taken our content marketing to new heights, allowing us to publish more frequently without compromising on quality. Highly recommended for anyone.",
    name: "Pavel M. - Canon",
    category: "Enterprise",
  },
  {
    company: `/public/images/client-logo-05.svg`,
    quote:
      "The AI-driven content tool has been a lifesaver for my marketing agency. We can now produce high-quality content for multiple clients quickly and efficiently. It's an invaluable asset to our team",
    name: "Miriam E. - Cadbury",
    category: "Enterprise",
  },
  {
    company: `/public/images/client-logo-06.svg`,
    quote:
      "I'm amazed at how well this AI-driven content tool performs. It's incredibly versatile and can generate content for blogs, social media, and even product descriptions effortlessly. It's fantastic!",
    name: "Eloise V. - Maffell",
    category: "eCommerce",
  },
  {
    company: `/public/images/client-logo-07.svg`,
    quote:
      "I was blown away by how easy it was to create my content using this tool! Within a few hours, I had a professional-looking platform up and running, and my client could not believe it.",
    name: "Pierre-Gilles L. - Binance",
    category: "Web Apps",
  },
  {
    company: `/public/images/client-logo-08.svg`,
    quote:
      "I've never been a fan of complicated website AI tools, which is why Open PRO is perfect for me. Its minimalist design and simple functionality make staying organized feel like second nature.",
    name: "Danielle K. - Forbes Inc.",
    category: "Enterprise",
  },
  {
    company: `/public/images/client-logo-09.svg`,
    quote:
      "I've never been one for coding, so finding an AI tool that doesn't require any technical skills was a dream come true. This tool exceeded my expectations, and I'm proud to show off my new stuff to friends.",
    name: "Mary P. - Ray Ban",
    category: "Web Apps",
  },
];

const TestimonialsSection = () => {
  const [activeFilter, setActiveFilter] = useState("View All");

  return (
    <section className=" text-white py-16 px-6">
      {/* title */}
      <div className="max-w-5xl mx-auto text-center mb-12">
        <h2 className="text-3xl font-medium mb-4">
          Don't take our word for it
        </h2>
        <p className="text-gray-300">
          We provide tech-first solutions that empower decision-makers to build
          healthier and happier workspaces from anywhere in the world.
        </p>
      </div>

      {/* filter btns*/}
      <div className="sm:flex sm:justify-center sm:block hidden">
        <div className="flex justify-center gap-4 mb-10 flex-wrap bg-gray-900 w-fit p-1.5 rounded-3xl">
          {filters.map((filter) => (
            <button
              key={filter.title}
              onClick={() => setActiveFilter(filter.title)}
              className={`px-3 py-1 flex gap-1.5 rounded-full text-sm font-medium ${
                activeFilter === filter.title
                  ? "bg-indigo-500 text-white"
                  : "bg-gray-700 text-gray-300 hover:bg-indigo-400 hover:text-white"
              }`}
            >
              {filter.icon}
              {filter.title}
            </button>
          ))}
        </div>
      </div>

      {/*cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
        {testimonials.map((t, index) => {
          const isBlurred =
            activeFilter !== "View All" && t.category !== activeFilter;
          return (
            <div
              key={index}
              className={` bg-gray-950 border border-gray-700 p-6 rounded-lg shadow-md transition duration-300 ${
                isBlurred ? "blur-xs opacity-80 pointer-events-none" : ""
              }`}
            >
              <img src={t.company} className=" m-1.5" alt="" />
              <p className="text-gray-300 text-sm mb-4">"{t.quote}"</p>
              <p className="text-sm text-gray-400">— {t.name}</p>
            </div>
          );
        })}
      </div>
      <section className=" bg-gradient-to-l from-gray-950 via-gray-900 to-gray-950 text-white mt-10 p-10 flex flex-col justify-center items-center text-center px-4">
        <h1 className="text-2xl  md:text-4xl font-[ne] font-bold mb-6">
          Join the content-first platform
        </h1>
        {/* get start btn */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-2 md:gap-7 pb-4">
          <button className="cta mb-2 sm:mb-0">
            <span>Get Started</span>
            <svg width="50px" height="10px" viewBox="0 0 13 10">
              <path d="M1,5 L11,5"></path>
              <polyline points="8 1 12 5 8 9"></polyline>
            </svg>
          </button>
          <Button
            className="bg-linear-to-b from-gray-800 to-gray-800/60 rounded-lg p-2 ml-0 sm:ml-7 mt-2 sm:mt-0 min-w-[110px]"
            variant="contained"
          >
            Schedule Demo
          </Button>
        </div>
      </section>
    </section>
  );
};

export default TestimonialsSection;
